package com.vicmatskiv.weaponlib;

public enum RenderableState {
	NORMAL, MODIFYING, MODIFYING_ALT, ZOOMING, RUNNING, 
	UNLOADING, RELOADING, LOAD_ITERATION, LOAD_ITERATION_COMPLETED, ALL_LOAD_ITERATIONS_COMPLETED,
	SHOOTING, AUTO_SHOOTING, RECOILED, ZOOMING_RECOILED, ZOOMING_SHOOTING, EJECT_SPENT_ROUND, 
	INSPECTING,
	PRONING, PRONING_AIMING, PRONING_SHOOTING, PRONING_RECOILED, DRAWING
	
}
