package com.vicmatskiv.weaponlib;

public enum RenderableState {

	NORMAL, MODIFYING, ZOOMING, RUNNING, UNLOADING, RELOADING, SHOOTING, AUTO_SHOOTING, RECOILED, ZOOMING_RECOILED, ZOOMING_SHOOTING, EJECT_SPENT_ROUND
}
